# Generated by Django 5.0.6 on 2024-05-18 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='actingMovie',
            new_name='actor_in_movie',
        ),
    ]
